# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tom Marien
subtitle:
description:
keywords:
author: Tom Marien
language: en
timezone: Europe/Brussels

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tommarien.github.io
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
#  line_number: true
#  auto_detect: false
#  tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
#  custom_css: 'path/to/your/custom.css'     # optional

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##date_format: YYYY-MM-DD
date_format: MMM D, YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 25
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

theme_config:
  # Customize the logo (i.e., the cactus) in the header.
  # Options:
  #   - enabled: whether to show (true) or hide (false) the logo.
  #   - width: width of the logo in pixel units
  #   - height: height of the logo in pixel units
  #   - url: where the logo can be found
  #   - gravatar: whether to use your Gravatar as the logo
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/logo.png
    gravatar: true

  # Customize the favicons.
  # Cactus supports a limited set of the three most important icons:
  #   - desktop: The classic favion.ico file.
  #   - android: A 192x192 PNG file.
  #   - apple:  A 180x180 PNG file.
  # These can be generated with http://realfavicongenerator.net/
  # Options:
  #   - url: where the icon can be found
  #   - gravatar: whether to create a favicon from your Gravatar
  favicon:
    desktop:
      url: /images/favicon.ico
      gravatar: true
    android:
      url: /images/favicon-192x192.png
      gravatar: true
    apple:
      url: /images/apple-touch-icon.png
      gravatar: true
  colorscheme: white
  nav:
    home: /
    articles: /archives/
    about: /about/
    search: /search/
    #projects: http://github.com/tommarien
  gravatar:
    email: tommarien@gmail.com
  google_analytics:
    enabled: true
    id: UA-50637133-1
  social_links:
    github: http://github.com/tommarien
    twitter: http://twitter.com/Tom_Marien
    #facebook: /
    linkedin: http://linkedin.com/in/tommarien
    mail: tommarien@gmail.com
  page_width: 48
  posts_overview:
    show_all_posts: false
    post_count: 10
    sort_updated: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:tommarien/tommarien.github.io.git
  branch: master
