version: 2.1
executors:
  node_lts: # declares a reusable executor
    docker:
      - image: node:12.16.3
    working_directory: ~/repo
jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v12-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-v12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Generate blog
          command: yarn hexo generate
      - persist_to_workspace:
          root: public
          paths:
            - '*'

  deploy:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v12-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - '1d:0c:ea:28:8a:4f:f0:5d:98:e1:ca:93:0f:38:d6:ab'
      - run:
          name: Setup git info
          command: |
            git config --global user.name "tommarien"
            git config --global user.email "tommarien@gmail.com"
      - run:
          name: Clone repo
          command: git clone git@github.com:tommarien/tommarien.github.io.git .deploy_git
      - run:
          name: Generate blog
          command: yarn hexo deploy
workflows:
  version: 2
  complete:
    jobs:
      - build
      - deploy:
          requires:
            - build
