version: 2.1
executors:
  node_lts: # declares a reusable executor
    docker:
      - image: node:16.14.0
    working_directory: ~/repo
jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v16-{{ checksum "package.json" }}
            - npm-v16-

      - run: npm install

      - save_cache:
          key: npm-v16-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate blog
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v16-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - '6a:5b:d9:5a:67:47:bd:4e:6e:0c:26:5f:d9:5e:df:61'
      - run:
          name: Setup git info
          command: |
            git config --global user.name "tommarien"
            git config --global user.email "tommarien@gmail.com"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy
workflows:
  version: 2
  complete:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
