version: 2.1
executors:
  node_lts: # declares a reusable executor
    docker:
      - image: node:14.18.0
    working_directory: ~/repo
jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v16-{{ checksum "package.json" }}
            - npm-v16-

      - run: npm install

      - save_cache:
          key: npm-v16-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate blog
          command: npm run build
      - persist_to_workspace:
          root: public
          paths:
            - '*'

  deploy:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v16-{{ checksum "package.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - '7e:7e:3f:c7:ca:20:ab:95:4d:cb:bd:5a:ae:a0:78:4a'
      - run:
          name: Setup git info
          command: |
            git config --global user.name "tommarien"
            git config --global user.email "tommarien@gmail.com"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy
workflows:
  version: 2
  complete:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
