name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      
      - name: Restore last modified time
        uses: srt32/git-actions@v0.0.3
        args: git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done

      - name: Build and Deploy
        uses: renzhaosy/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.DeployToken }}
          PUBLISH_REPOSITORY: tommarien/tommarien.github.io # The repository the action should deploy to.
          BRANCH: master # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
